
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Popup      <small><?= cclang('detail', ['Popup']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/fastcon_home_popup'); ?>">Popup</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Popup</h3>
                     <h5 class="widget-user-desc">Detail Popup</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_fastcon_home_popup" id="form_fastcon_home_popup" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_home_popup->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Popup Title </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_home_popup->popup_title); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Popup Title En </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_home_popup->popup_title_en); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Body </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_home_popup->body); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Body En </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_home_popup->body_en); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Btn Primary Text </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_home_popup->btn_primary_text); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Btn Primary Text En </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_home_popup->btn_primary_text_en); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Btn Primary Link </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_home_popup->btn_primary_link); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Btn Secondary Text </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_home_popup->btn_secondary_text); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Btn Secondary Text En </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_home_popup->btn_secondary_text_en); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Btn Secondary Link </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_home_popup->btn_secondary_link); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Active </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_home_popup->active); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('fastcon_home_popup_update', function() use ($fastcon_home_popup){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit fastcon_home_popup (Ctrl+e)" href="<?= site_url('administrator/fastcon_home_popup/edit/'.$fastcon_home_popup->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Fastcon Home Popup']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/fastcon_home_popup/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Fastcon Home Popup']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
