
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Product      <small><?= cclang('detail', ['Product']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/fastcon_product'); ?>">Product</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Product</h3>
                     <h5 class="widget-user-desc">Detail Product</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_fastcon_product" id="form_fastcon_product" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product->product_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Category </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product->category_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Name </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product->product_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Slug </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product->product_slug); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Product Images </label>
                        <div class="col-sm-8">
                             <?php if (!empty($fastcon_product->product_images)): ?>
                             <?php foreach (explode(',', $fastcon_product->product_images) as $filename): ?>
                               <?php if (is_image($fastcon_product->product_images)): ?>
                                <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/fastcon_product/' . $filename; ?>">
                                  <img src="<?= BASE_URL . 'uploads/fastcon_product/' . $filename; ?>" class="image-responsive" alt="image fastcon_product" title="product_images fastcon_product" width="40px">
                                </a>
                                <?php else: ?>
                                <label>
                                  <a href="<?= BASE_URL . 'administrator/file/download/fastcon_product/' . $filename; ?>">
                                   <img src="<?= get_icon_file($filename); ?>" class="image-responsive" alt="image fastcon_product" title="product_images <?= $filename; ?>" width="40px"> 
                                 <?= $filename ?>
                               </a>
                               </label>
                              <?php endif; ?>
                            <?php endforeach; ?>
                          <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Desc </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product->product_desc); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Spec </label>
                        <div class="col-sm-8">
                             <?php if (is_image($fastcon_product->spec)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/fastcon_product/' . $fastcon_product->spec; ?>">
                                <img src="<?= BASE_URL . 'uploads/fastcon_product/' . $fastcon_product->spec; ?>" class="image-responsive" alt="image fastcon_product" title="spec fastcon_product" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/fastcon_product/' . $fastcon_product->spec; ?>">
                                 <img src="<?= get_icon_file($fastcon_product->spec); ?>" class="image-responsive" alt="image fastcon_product" title="spec <?= $fastcon_product->spec; ?>" width="40px"> 
                               <?= $fastcon_product->spec ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Cara Pasang </label>
                        <div class="col-sm-8">
                             <?php if (is_image($fastcon_product->cara_pasang)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/fastcon_product/' . $fastcon_product->cara_pasang; ?>">
                                <img src="<?= BASE_URL . 'uploads/fastcon_product/' . $fastcon_product->cara_pasang; ?>" class="image-responsive" alt="image fastcon_product" title="cara_pasang fastcon_product" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/fastcon_product/' . $fastcon_product->cara_pasang; ?>">
                                 <img src="<?= get_icon_file($fastcon_product->cara_pasang); ?>" class="image-responsive" alt="image fastcon_product" title="cara_pasang <?= $fastcon_product->cara_pasang; ?>" width="40px"> 
                               <?= $fastcon_product->cara_pasang ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Certificate </label>
                        <div class="col-sm-8">
                             <?php if (is_image($fastcon_product->certificate)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/fastcon_product/' . $fastcon_product->certificate; ?>">
                                <img src="<?= BASE_URL . 'uploads/fastcon_product/' . $fastcon_product->certificate; ?>" class="image-responsive" alt="image fastcon_product" title="certificate fastcon_product" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/fastcon_product/' . $fastcon_product->certificate; ?>">
                                 <img src="<?= get_icon_file($fastcon_product->certificate); ?>" class="image-responsive" alt="image fastcon_product" title="certificate <?= $fastcon_product->certificate; ?>" width="40px"> 
                               <?= $fastcon_product->certificate ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                      
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('fastcon_product_update', function() use ($fastcon_product){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit fastcon_product (Ctrl+e)" href="<?= site_url('administrator/fastcon_product/edit/'.$fastcon_product->product_id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Fastcon Product']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/fastcon_product/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Fastcon Product']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
