
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Transactions      <small><?= cclang('detail', ['Transactions']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/fastcon_product_orders'); ?>">Transactions</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Transactions</h3>
                     <h5 class="widget-user-desc">Detail Transactions</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_fastcon_product_orders" id="form_fastcon_product_orders" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->order_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Code </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->order_code); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Status </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->order_status); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Member Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->member_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Guest Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->guest_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Payer Name </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->payer_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Payer Email </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->payer_email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Category Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_category_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Category Name </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_category_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Category Name En </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_category_name_en); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Name </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Product Images </label>
                        <div class="col-sm-8">
                             <?php if (is_image($fastcon_product_orders->product_images)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/fastcon_product_orders/' . $fastcon_product_orders->product_images; ?>">
                                <img src="<?= BASE_URL . 'uploads/fastcon_product_orders/' . $fastcon_product_orders->product_images; ?>" class="image-responsive" alt="image fastcon_product_orders" title="product_images fastcon_product_orders" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/fastcon_product_orders/' . $fastcon_product_orders->product_images; ?>">
                                 <img src="<?= get_icon_file($fastcon_product_orders->product_images); ?>" class="image-responsive" alt="image fastcon_product_orders" title="product_images <?= $fastcon_product_orders->product_images; ?>" width="40px"> 
                               <?= $fastcon_product_orders->product_images ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Variant Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->variant_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sku </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->sku); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Option1 Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_option1_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Option1 Name </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_option1_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Option1 Name En </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_option1_name_en); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Option1 Value Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_option1_value_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Option1 Value </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_option1_value); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Option2 Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_option2_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Option2 Name </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_option2_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Option2 Name En </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_option2_name_en); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Option2 Value Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_option2_value_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Option2 Value </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->product_option2_value); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Price </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->price); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Discount </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->discount); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Qty </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->qty); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Subtotal </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->subtotal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Cost </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->shipping_cost); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Total </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->total); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Voucher Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->voucher_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Voucher Code </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->voucher_code); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Voucher Discount </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->voucher_discount); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Voucher Start Date </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->voucher_start_date); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Voucher End Date </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->voucher_end_date); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Member Address Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->member_address_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Penerima </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->nama_penerima); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No Telp </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->no_telp); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Province Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->province_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Province Name </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->province_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Provinsi </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->provinsi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kabupaten </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->kabupaten); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kecamatan </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->kecamatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kelurahan </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->kelurahan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Pos </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->kode_pos); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alamat Lengkap </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->alamat_lengkap); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Courier Name </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->courier_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Courier Phone </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->courier_phone); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Xendit Inv Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->xendit_inv_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">External Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->external_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">User Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->user_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->status); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Amount </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->amount); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Expiry Date </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->expiry_date); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Invoice Url </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->invoice_url); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Xendit Response </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->xendit_response); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Created </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_product_orders->created); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('fastcon_product_orders_update', function() use ($fastcon_product_orders){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit fastcon_product_orders (Ctrl+e)" href="<?= site_url('administrator/fastcon_product_orders/edit/'.$fastcon_product_orders->order_id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Fastcon Product Orders']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/fastcon_product_orders/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Fastcon Product Orders']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
