
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Banner      <small><?= cclang('detail', ['Banner']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/fastcon_banner'); ?>">Banner</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Banner</h3>
                     <h5 class="widget-user-desc">Detail Banner</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_fastcon_banner" id="form_fastcon_banner" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_banner->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Bg Img </label>
                        <div class="col-sm-8">
                             <?php if (is_image($fastcon_banner->bg_img)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/fastcon_banner/' . $fastcon_banner->bg_img; ?>">
                                <img src="<?= BASE_URL . 'uploads/fastcon_banner/' . $fastcon_banner->bg_img; ?>" class="image-responsive" alt="image fastcon_banner" title="bg_img fastcon_banner" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/fastcon_banner/' . $fastcon_banner->bg_img; ?>">
                                 <img src="<?= get_icon_file($fastcon_banner->bg_img); ?>" class="image-responsive" alt="image fastcon_banner" title="bg_img <?= $fastcon_banner->bg_img; ?>" width="40px"> 
                               <?= $fastcon_banner->bg_img ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Fg Img </label>
                        <div class="col-sm-8">
                             <?php if (is_image($fastcon_banner->fg_img)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/fastcon_banner/' . $fastcon_banner->fg_img; ?>">
                                <img src="<?= BASE_URL . 'uploads/fastcon_banner/' . $fastcon_banner->fg_img; ?>" class="image-responsive" alt="image fastcon_banner" title="fg_img fastcon_banner" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/fastcon_banner/' . $fastcon_banner->fg_img; ?>">
                                 <img src="<?= get_icon_file($fastcon_banner->fg_img); ?>" class="image-responsive" alt="image fastcon_banner" title="fg_img <?= $fastcon_banner->fg_img; ?>" width="40px"> 
                               <?= $fastcon_banner->fg_img ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Title </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_banner->title); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Title En </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_banner->title_en); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Caption </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_banner->caption); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Caption En </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_banner->caption_en); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Primary Btn </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_banner->primary_btn); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Primary Btn En </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_banner->primary_btn_en); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Primary Btn Link </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_banner->primary_btn_link); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Secondary Btn </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_banner->secondary_btn); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Secondary Btn En </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_banner->secondary_btn_en); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Secondary Btn Link </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_banner->secondary_btn_link); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('fastcon_banner_update', function() use ($fastcon_banner){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit fastcon_banner (Ctrl+e)" href="<?= site_url('administrator/fastcon_banner/edit/'.$fastcon_banner->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Fastcon Banner']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/fastcon_banner/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Fastcon Banner']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
