
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Marketplace      <small><?= cclang('detail', ['Marketplace']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/fastcon_marketplace'); ?>">Marketplace</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Marketplace</h3>
                     <h5 class="widget-user-desc">Detail Marketplace</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_fastcon_marketplace" id="form_fastcon_marketplace" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_marketplace->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Icon </label>
                        <div class="col-sm-8">
                             <?php if (is_image($fastcon_marketplace->icon)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/fastcon_marketplace/' . $fastcon_marketplace->icon; ?>">
                                <img src="<?= BASE_URL . 'uploads/fastcon_marketplace/' . $fastcon_marketplace->icon; ?>" class="image-responsive" alt="image fastcon_marketplace" title="icon fastcon_marketplace" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/fastcon_marketplace/' . $fastcon_marketplace->icon; ?>">
                                 <img src="<?= get_icon_file($fastcon_marketplace->icon); ?>" class="image-responsive" alt="image fastcon_marketplace" title="icon <?= $fastcon_marketplace->icon; ?>" width="40px"> 
                               <?= $fastcon_marketplace->icon ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Link </label>

                        <div class="col-sm-8">
                           <?= _ent($fastcon_marketplace->link); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('fastcon_marketplace_update', function() use ($fastcon_marketplace){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit fastcon_marketplace (Ctrl+e)" href="<?= site_url('administrator/fastcon_marketplace/edit/'.$fastcon_marketplace->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Fastcon Marketplace']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/fastcon_marketplace/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Fastcon Marketplace']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
